# Generated by Django 2.0.13 on 2020-02-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
