# Generated by Django 2.0.13 on 2020-03-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_auto_20200228_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='offer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
